routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Jobs\SendEmail;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('sendEmail' , function (){
////    Job::dispatch()->onQueue('emails');
//    SendEmail::dispatch()
//        ->delay(now()->addSeconds(5));
//
//    return "email sent successfully";
//});

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/post/{id}/like' , 'PostController@like')->name('post.like');
Route::any('/post/{id}/dislike' , 'PostController@dislike')->name('post.dislike');
Route::any('/post/{id}/comment' , 'PostController@commentStore')->name('post.comment');
Route::resource('post' , 'PostController');
//Route::resource('post' , 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Post extends Model
{
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function comment()
    {
        return $this->hasMany(Comment::class , 'post_id' , 'id');
    }



    public function getTextAttribute($value){
        return ucfirst($value);

    }
    public function likes()
    {
        return $this->belongsToMany(User::class,'post_like','','','','');
    }
    public function check_like()
    {
        return $this->likes()->where('user_id', Auth::id());
    }


    protected $guarded = [];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Country;
use App\Events\Comments;
use App\Http\Requests\PostRequest;
use App\Jobs\commentMailJob;
use App\Jobs\SendEmail;
use App\Mail\PostMail;
use App\Post;
use App\post_like;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PHPUnit\Framework\Constraint\Count;
use App\Mail\RegistrationMail;
use Illuminate\Support\Facades\Mail;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::check())
        {
            //
        }
        else{
            return view('auth/login');
        }
        if (isset(\request()->countrySelect)) {

            $post = Country::find(\request()->countrySelect)->post;
        } else {
            $post = Post::with('comment','check_like')->get();

        }
//        dd($post[0]->check_like);
        $country = Country::all();
//        $post = Post::find(83);
//        dd($post->likes());

        return view('post/displayPost')->with(['post' => $post])->with('country', $country);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user())
        {
            return view('post/addPost');
        }
        else{
            return view('auth/login');
        }

    }

    /**
     * Store a newly created resource in comment storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function commentStore(Request $request, $id)
    {
        $validatedData = $request->validate([
            'comment' => 'required|max:255',

        ]);

        $comments = Comment::with('Post')->get();
//        dd($comments[0]->text);
        $comment = Comment::create([
            'post_id' => $id,
            'user_id' => auth::id(),
            'text' => $request->comment,
        ]);

        commentMailJob::dispatch()
            ->delay(now()->addSeconds(5));

        event(new Comments('commentListener has sent an email on your address'));
        return back()->with(['comments' => $comments]);

    }


    /**
     * Store a newly created resource in comment storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */

public function like($id)
{
    $post = Post::find($id);
    $post->likes()->attach(['user_id' => auth::id()]);
    return back();
}

public function dislike($id)
{
    $post = Post::find($id);
    $post->likes()->detach(['user_id' => auth::id()]);
    return back();
}

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
//        $validatedData = $request->validate([
//            'file' => 'mimes:jpeg,png,jpg,avi,mp4,mov,svg',
//            'caption' => 'required'
//        ]);

        $url = $request->file('file');

        $extension = $url->getClientOriginalExtension();

        $urlPath = $url->storeAs('post', $url->getClientOriginalName(), 'public');


        if ($extension == "jpeg" || $extension == "jpg" || $extension == "svg" || $extension == "png") {
            $postType = 'photo';

        }

        if ($extension == "mp4" || $extension == "mov" || $extension == "avi") {
            $postType = 'video';
        }

        $post = Post::create([
            'user_id' => Auth::id(),
            'url' => $urlPath,
            'text' => $request->caption,
            'post_type' => $postType
        ]);
//        dd($urlPath);

        Mail::to('test@gmail.com')->send(new PostMail($post));
            // return redirect()->route('post.index');
        return redirect()->action('PostController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

//
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        $post->delete();
        return back();

    }
}

resources/views/post/addPost.blade.php
@extends('layouts.app')
<!-- {{--@extends('html')--}} -->
@section('title' , 'Add Post')
@section('js')


<!-- Theme JS files -->
<script type="text/javascript" src="{{ asset('assets/js/plugins/uploaders/fileinput.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
<script type="text/javascript" src="{{ url('assets/js/pages/uploader_bootstrap.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js')}}"></script>
<script>
var modalTemplate = '<div class="modal-dialog modal-lg" role="document">\n' +
    '  <div class="modal-content">\n' +
    '    <div class="modal-header">\n' +
    '      <div class="kv-zoom-actions btn-group">{toggleheader}{fullscreen}{borderless}{close}</div>\n' +
    '      <h6 class="modal-title">{heading} <small><span class="kv-zoom-title"></span></small></h6>\n' +
    '    </div>\n' +
    '    <div class="modal-body">\n' +
    '      <div class="floating-buttons btn-group"></div>\n' +
    '      <div class="kv-zoom-body file-zoom-content"></div>\n' + '{prev} {next}\n' +
    '    </div>\n' +
    '  </div>\n' +
    '</div>\n';

// Buttons inside zoom modal
var previewZoomButtonClasses = {
    toggleheader: 'btn btn-default btn-icon btn-xs btn-header-toggle',
    fullscreen: 'btn btn-default btn-icon btn-xs',
    borderless: 'btn btn-default btn-icon btn-xs',
    close: 'btn btn-default btn-icon btn-xs'
};

// Icons inside zoom modal classes
var previewZoomButtonIcons = {
    prev: '<i class="icon-arrow-left32"></i>',
    next: '<i class="icon-arrow-right32"></i>',
    toggleheader: '<i class="icon-menu-open"></i>',
    fullscreen: '<i class="icon-screen-full"></i>',
    borderless: '<i class="icon-alignment-unalign"></i>',
    close: '<i class="icon-cross3"></i>'
};

// File actions
var fileActionSettings = {
    zoomClass: 'btn btn-link btn-xs btn-icon',
    zoomIcon: '<i class="icon-zoomin3"></i>',
    dragClass: 'btn btn-link btn-xs btn-icon',
    dragIcon: '<i class="icon-three-bars"></i>',
    removeClass: 'btn btn-link btn-icon btn-xs',
    removeIcon: '<i class="icon-trash"></i>',
    indicatorNew: '<i class="icon-file-plus text-slate"></i>',
    indicatorSuccess: '<i class="icon-checkmark3 file-icon-large text-success"></i>',
    indicatorError: '<i class="icon-cross2 text-danger"></i>',
    indicatorLoading: '<i class="icon-spinner2 spinner text-muted"></i>'
};




$('.file-input').fileinput({
    browseLabel: 'Browse',
    browseIcon: '<i class="icon-file-plus"></i>',
    uploadIcon: '<i class="icon-file-upload2"></i>',
    removeIcon: '<i class="icon-cross3"></i>',
    layoutTemplates: {
        icon: '<i class="icon-file-check"></i>',
        modal: modalTemplate
    },
    initialCaption: "No file selected",
    previewZoomButtonClasses: previewZoomButtonClasses,
    previewZoomButtonIcons: previewZoomButtonIcons,
    fileActionSettings: fileActionSettings
});
</script>
<!-- /theme JS files -->

@endsection

@section('content')

<div class="container ">
<h3 class="text-center">Add Post</h3>
<br>

<div class="panel panel-flat">
    <div class="panel-body">

	
        <form class="form-horizontal" action="{{ route('post.store') }}" method="POST"  enctype="multipart/form-data">
            @csrf

            <div class="form-group">
                <label class="col-lg-2 control-label text-semibold">Post upload:</label>
                <div class="col-lg-10 ">
                    <input type="file" class="file-input" name="file">
                    <div style="color:red">
                    @error('file')
                    {{ $message}}
                    @enderror
                    </div>
					<textarea name="caption" class="form-control my-5" placeholder="Caption Goes Here" id="caption" cols="30" rows="10"></textarea>
                    <div style="color:red">
                    @error('caption')
                    {{$message}}
                    @enderror
                    </div>
              
                </div>
            </div>
            <!-- <button type="submit" class="btn btn-primary " value="Add Post">Post</button> -->


        </form>

    </div>
</div>
</div>
@endsection

resources/views/post/displayPost.blade.php
@extends('layouts.app')
@section('title' , 'Display Post')

@section('js')

<!-- Theme JS files -->
<!-- Theme JS files -->

<!-- <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/bootstrap_select.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/pages/form_bootstrap_select.js')}}"></script>

<script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js')}}"></script> -->

<script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/core.min.js') }}"></script>

<script type="text/javascript" src="{{asset('assets/js/plugins/forms/styling/uniform.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/pages/form_selectbox.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/selectboxit.min.js') }}"></script>
<script type="text/javascript" src="{{asset('assets/js/plugins/ui/ripple.min.js')}}"></script>
<!-- /theme JS files -->

@endsection

@section('content')

<div class="container text-center">
    <div class="panel panel-flat">
        <div class="panel-body">
            <h3 class="text-center">News Feed</h3>


            {{count($post) . " Posts found"}}
            <br><br>


            <form action="{{ route('post.index') }}" class="form-horizontal" method="get">

                <select name="countrySelect" class="selectbox form-control ">
                    <option value="">Select Country</option>
                    @foreach($country as $singleCountry)
                    <option value="{{$singleCountry->id}}">{{$singleCountry->name}}</option>
                    @endforeach
                </select>
                <button type="submit" value="show" class="my-5 btn btn-primary">Show</button>
            </form>

        </div>
    </div>

    @foreach($post as $singlePost)
    <div class="panel panel-flat">
        <div class="panel-body">
            {{ $loop->iteration}} <b> {{$singlePost->user->name}}</b> posted a {{$singlePost->post_type}}
            @if(auth::id() == $singlePost->user_id)
            <form action="{{ route('post.destroy' , ['post' => $singlePost->id])}}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit">Delete Post</button>
            </form>
            @endif
            <br>

            @if($singlePost->post_type == 'photo')
            <img src="storage/{{$singlePost->url}}" width="300px" height="200px"></img>
            @endif
            @if($singlePost->post_type == 'video')
            <video src="storage/{{ $singlePost->url}}" width="300px" height="200px" controls></video>
            @endif
            <br>
            <b> {{$singlePost->user->name}}</b>
            <div class="text-wrap"> {{'- ' .$singlePost->text}}</div>


            {{--        @dd($singlePost->check_like())--}}
            @if(sizeof($singlePost->check_like) == null)
            <a href="{{ route('post.like' , ['id' => $singlePost->id] ) }}">like</a>
            @else
            <a href="{{ route('post.dislike' , ['id' => $singlePost->id] ) }}">dislike</a>
            @endif
            <br>
            <b>Comments</b><br>
            @foreach($singlePost->comment as $comment)

            <b>{{$comment->user->name}}</b> {{$comment->text}}
            <br>
            @endforeach


            <form action="{{ route('post.comment' , ['id'=> $singlePost->id])}}" method="post">
                @csrf
                <b class="col-md-2 offset-3">{{auth::user()->name}} </b>
                <input type="text" class="col-md-3 form-control"
                    name="comment" placeholder="Comment here">
{{--                <div style="color: red">--}}
{{--                    @error('comment')--}}
{{--                    {{$message}}--}}
{{--                    @enderror--}}
{{--                </div>--}}


                <br>
                <button type="submit" class="btn  btn-primary btn-rounded">Comment</button>
                <br>
            </form>
            <br><br><br>
        </div>
    </div>
    @endforeach

    @endsection

    <script>
    (".selectbox").selectBoxIt({
        autoWidth: false
    });
    </script>
</div>