routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Jobs\SendEmail;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('sendEmail' , function (){
////    Job::dispatch()->onQueue('emails');
//    SendEmail::dispatch()
//        ->delay(now()->addSeconds(5));
//
//    return "email sent successfully";
//});

Route::get('/home', 'HomeController@index')->name('home');
Route::any('/post/{id}/like' , 'PostController@like')->name('post.like');
Route::any('/post/{id}/dislike' , 'PostController@dislike')->name('post.dislike');
Route::any('/post/{id}/comment' , 'PostController@commentStore')->name('post.comment');
Route::resource('post' , 'PostController');
//Route::resource('post' , 'PostController');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
{{--            <div class="card">--}}
{{--                <div class="card-header"></div>--}}
{{--                <div class="card-body">--}}
{{--                    @if (session('status'))--}}
{{--                        <div class="alert alert-success" role="alert">--}}
{{--                            {{ session('status') }}--}}
{{--                        </div>--}}
{{--                    @endif--}}
{{--                </div>--}}
{{--            </div>--}}

            <a href="{{ route('post.create')}}">Add Post</a>
            <a href="{{ route('post.index')}}">Display Post</a>

        </div>
    </div>
</div>
@endsection

resources/views/html.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> @yield('title')</title>
</head>
<body>

@yield('content')

</body>
</html>